### PR TITLE
Fixed errors using latest tox>=3.8.0

### PR DESCRIPTION
**Pull request by jackton1**

### CODE REVIEW

**Review by asottile — APPROVED** [review]
CC @gaborbernat

**Review by gaborbernat — APPROVED** [review]

**Review by gaborbernat — COMMENTED** [review]
I would put the 3.8 greater restriction inside setup.py

**Comment by asottile** [comment]
yep, will do when releasing -- mostly a heads up in case other plugins are also using these interfaces (and therefore broken)

**Comment by asottile** [comment]
actually, looks like according to the test and linters this is broken as written @jackton1 can you fix that up?

**Comment by jackton1** [comment]
Sure

**Comment by jackton1** [comment]
travis CI crawls for sure.

**Comment by asottile** [comment]
Released as 1.6.0

**Pull request merged**
