### PR TITLE
Remove [testenv:venv] now that `tox --devenv` is a thing

### PR DESCRIPTION
**Pull request by asottile**
Committed via https://github.com/asottile/all-repos

### CODE REVIEW

**Comment by asottile** [comment]
@webknjaz looks like the bot is in too many placess :laughing:

**Comment by gaborbernat** [comment]
Or just you changelog missing 😆

**Comment by asottile** [comment]
lol, changelogs

**Comment by webknjaz** [comment]
@asottile I assume that @gaborbernat installed it into all repos. I cannot see this info myself because I'm not in the org.

And currently, it processes hooks from everywhere it's installed, not requiring a special config for enabling it explicitly for the repo.

**Comment by gaborbernat** [comment]
Fixed it now.

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
